In [1]:
# Di python tidak perlu untuk menentukan tipe data
a = 5
b = 7.2
c = False
d = "Nama"

# Gunakan print() untuk mencetak output
print(a)
# Gunakan type() untuk mengetahui tipe data suatu variable
print(type(a))
print(type(b))
print(type(c))
print(type(d))

5
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>

In [2]:
# Dapat melakukan casting untuk nilai variable
e = float(a)
print(e)
print(type(e))

5.0
<class 'float'>

Penamaan Variable
+ hanya memuat karakter alpha-numeric dan underscore
+ diawali dengan huruf maupun underscore
+ tidak dapat diawali oleh angka
+ tidak dapat menggunakan penamaan keyword pada python
+ bersifat case-sensitive

In [3]:
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"

# Untuk multi-words, silahkan gunakan camelCase PascalCase snake_case

In [4]:
# 1 nilai untuk beberapa variable
x = y = z = 0
print(x)
print(y)
print(z)

# beberapa nilai untuk beberapa variable
a, b, c = 1, 2, 3
print(a)
print(b)
print(c)

0
0
0
1
2
3

In [5]:
# Selain tipe data dasar, terdapat juga:
# list, dictionary, tuple, set, dll.
fruits = ["apple", "banana", "cherry"]
print(fruits)

['apple', 'banana', 'cherry']

In [6]:
# Destructuring
a, b, c = fruits
print(a)
print(b)
print(c)

# Destructuring skip value
d, _, e = [1, 2, 3]

apple
banana
cherry

In [7]:
# Destructuring some values
head, *tail = [1, 2, 3, 4, 5]
print(head)
print(tail)

*head, tail = [1, 2, 3, 4, 5]
print(head)
print(tail)

head, *body, tail = [1, 2, 3, 4, 5]
print(head)
print(body)
print(tail)

1
[2, 3, 4, 5]
[1, 2, 3, 4]
5
1
[2, 3, 4]
5

python data types:\
https://www.w3schools.com/python/python_datatypes.asp

In [8]:
# Slicing
# syntax: [start:end]
numbers = [0, 1, 2, 3, 4, 5]

# ambil dari index 1 hingga SEBELUM index 3
print(numbers[1:3])

# ambil 3 pertama
print(numbers[:3])

# ambil dari index ke 2 hingga akhir
print(numbers[2:])

# contoh dengan negative index
print(numbers[-4:-1])

[1, 2]
[0, 1, 2]
[2, 3, 4, 5]
[2, 3, 4]

Nilai Boolean diawali dengan kapital (`True` & `False`)
+ String apapun bernilai `True`, kecuali _empty string_
+ Number apapun bernilai `True`, kecuali __0__
+ list, tuple, set, maupun dictionary bernilai `True` selama beranggota (tidak kosong)

Operator python:\
https://www.w3schools.com/python/python_operators.asp
+ arithmetic
+ assignment
+ comparison
+ logical
+ identity
+ membership
+ bitwise
- precedence

In [9]:
# Conditionals

# Syntax:
# if <condition>:
#   <execution>
# elif <condition>:
#   <execution>
# ...
# else:
#   <execution>
# PERHATIKAN INDENTASI untuk block execution

# short hand if (one line)
print("OK" if 5 > 3 else "HMM")

# bila block execution tidak memiliki apapun untuk dilaksanakan
# isi dengan keyword pass
if (5 in [1, 2, 3, 4, 5]):
  pass

OK

In [10]:
# Loops pada python mirip seperti bahasa pemrograman lain

# namun while pada python juga dapat menerapkan else
i = 1
while i < 6:
  print(i)
  i += 1
else:
  print("i is no longer less than 6")

# for pada python juga dapat dituliskan dalam one line
codes = [f"CODE-{x}" for x in "ABCDE"]
print(codes)

1
2
3
4
5
i is no longer less than 6
['CODE-A', 'CODE-B', 'CODE-C', 'CODE-D', 'CODE-E']

In [11]:
# self-defined function pada python menggunakan syntax berikut
# def function_name(arguments):
#   <execution>
#   return <value>

def print_name(firstname, lastname):
  print(firstname + " " + lastname)

def return_combined_name(firstname, lastname):
  return f"{firstname} {lastname}"

def print_names(*names):
  for name in names:
    print(name)

print_name("Hendry", "Winata")
print(return_combined_name("H","W"))
print_names("Andi", "Budi", "Cindy")

# function juga dapat menerapkan keyword pass
def noneedfunction():
  pass

Hendry Winata
H W
Andi
Budi
Cindy

In [12]:
# lambda function
# small anonymous function
# take argument(s), only one expression
# syntax:
# lamda argument(s) : expression
power = lambda x, y : x ** y
print(power(2, 3))

8

In [13]:
# sebagai tambahan, terdapat juga variable global
x = 100
def value_parser():
  global x
  x = "global variable"
  y = "not a global variable"

print(x)

value_parser()
print(x)

# print(y)

100
global variable